made dune easy to integrate with C++ projects (i.e., extern C pragmas…
ix-project/dune pull request #11
Opened 2018-07-28 21:02 UTC by ustiugov

… added to headers)

2018-08-15 15:42 UTC, prekageo requested changes

2018-08-15 15:42 UTC, prekageo commented on libdune/dune.h
> + #ifdef __cplusplus
Please remove the leading space from each line.

2018-08-15 15:42 UTC, prekageo commented on libdune/cpu-x86.h
> + #ifdef __cplusplus
Why do you need extern "C" in this file?

2018-08-16 18:08 UTC, ustiugov commented
Thanks, George. Updated accordingly

2018-08-20 10:53 UTC, merged