TLB shootdown
ix-project/dune pull request #6
Opened 2017-01-09 16:53 UTC by basicthinker

I think TLB shootdown is a very necessary function for Dune, because any thread that changes page mappings need this to let other threads know. Implementation details are mentioned in the commit messages. The idea is to reuse the existing inter-processor interrupt mechanism in the Linux kernel, instead of remaking one in libdune, for both simplicity and reliability.

A test is included. BTW, that program is in C++, so it can be a reference for users who want to use Dune with C++.

2017-01-17 14:18 UTC, prekageo requested changes
I have 2 comments / questions:
* I thought TLB shootdown refers to the operation where a core A invalidates the TLB of core B. A minor terminology issue.
* Why do you need to do that through the Dune kernel module? Can't libdune handle it?

2017-01-17 14:18 UTC, prekageo commented on libdune/dune.h
> +	dune_fd = open("/dev/dune", O_RDWR);
Resource leak. You should close the file descriptor.

2017-01-22 14:39 UTC, basicthinker commented
1. According to [this paper](https://pdfs.semanticscholar.org/6060/f21eb426c2b9b12d91fdfd00f4b775024b15.pdf) (PACT '11) and [these answers](http://stackoverflow.com/questions/3748384/what-is-tlb-shootdown), a TLB shootdown refers to invalidation of TLBs on all other processors. But I think it can also refer to do invalidation on another single processor, as you pointed out. It is not a strictly defined term.

2. There is a trade-off. It is possible to implement an inter-processor interrupt mechanism in libdune. That way should have performance advantage, but it is a duplicate of the Linux kernel's [facility](http://lxr.free-electrons.com/source/kernel/smp.c#L389). The other way is to reuse existing kernel code by communicating with the Dune device. It incurs extra overhead but the implementation is simple and reliable.

Close of the file descriptor is added.

2017-01-26 10:04 UTC, prekageo commented
1. In your test case, why do you do the TLB shootdown inside the page fault handler? Is that common practice? I would expect to see the shootdown immediately after modifying a page table entry.
2. Your solution performs a VM exit for each TLB shootdown. Although valid, this is not the best implementation in terms of performance. Ideally, you would like to perfom the TLB shootdown without exiting from VMX non-root mode. Do you think this is possible?

2018-06-12 09:37 UTC, closed without merging